[package]
name = "rustybeer"
version = "0.1.0"
authors = ["Heikki Hellgren <heiccih@gmail.com>", "mlatief", "Joseph Russell"]
edition = "2018"

[dependencies]
clap = "2.33.*"
measurements = "0.2.1"
regex = "1"
